server:
  port: 9876

spring:
  application:
    name: rbac
  profiles:
    active: dev

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.rbac.model
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  level:
    root: info
    com.rbac: debug
  file: /var/logs/rbac.log


