server:
  port: 9876

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.102:3306/rbac?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Qwer!@#$1234